name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build --tag tanu3693/dockershellimage .
        docker login -u tanu3693 -p ${{ secrets.DOCKER_PASSWORD }}
        docker push tanu3693/dockershellimage
